### ISSUE TITLE
Week 5/Checkpoint 2 ready for review

### ISSUE THREAD

**Issue by akcuster** [akcuster/plantParentHelper#4]
@pawaitemadisoncollege I know it's probably too late to get points for week 5, but I do have it completed now and feedback is still valuable I did get the feedback for James' presentation entered in last week, but I completely forgot to give you a heads up. I should be all set for the checkpoint 2 review as well.

**Comment by akcuster** [comment]
I forgot to add my reflection... 
The key takeaways were learning how to add the database relationships to the entities and getting very familiar with the various error messages that can pop up when things aren't quite right.

My biggest challenge was making sure I had all of the correct resources in the test directory and that all of the mappings were up to date.

The problems I overcame were mainly learning how to decipher error messages due to the challenges stated above. I mostly relied on posts in the slack channels and the knowledge I've already gained to figure them out.

**Comment by pawaitemadisoncollege** [comment]
Week 5 Feedback (I will circle back on Checkpoint 2, as I want to catch up on regular weekly work feedback first!)

Great job implementing the GenericDao as part of the week 5 work. That'll make things move more quickly as you add more tables/entities!

- [ ] You did a nice job with unit testing the common scenarios! Also think about testing the delete scenarios in one-to-many relationships more fully. For example, if a plant is deleted, what should happen to the user? What if a user is deleted? Write tests to make sure whatever should happen, does happen.

**Comment by pawaitemadisoncollege** [comment]
CP2 Feedback.  Completing much of the weekly work in your indie project has paid off! CP2 looks good!  Just a few thoughts as I reviewed the work here so far:

- [ ] DB design will also need a role table (tomcat authentication requirement)
- [ ] Where will plant care/requirements be kept?
